/**
 * Spec 987 — interactive always-on hot tier.
 *
 * CLAUDE.md / AGENTS.md are static files with no runtime loader, so the hot tier
 * reaches interactive sessions as a GENERATED managed block written at
 * `codev init` / `codev update` time. The block is delimited by explicit markers;
 * regeneration replaces only the block and preserves all surrounding user content
 * (non-clobbering). The single source of truth is the hot files
 * (codev/resources/{arch,lessons}-critical.md), resolved via the four-tier chain.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { resolveCodevFile } from './skeleton.js';

export const HOT_BLOCK_BEGIN = '<!-- BEGIN CODEV HOT CONTEXT (generated — do not edit) -->';
export const HOT_BLOCK_END = '<!-- END CODEV HOT CONTEXT -->';

/** Root docs that carry the managed block (kept byte-identical to each other). */
export const ROOT_DOCS = ['CLAUDE.md', 'AGENTS.md'] as const;

/**
 * Read the capped hot files (arch-critical.md + lessons-critical.md) via the
 * four-tier resolver. Shared by porch prompt injection and the interactive block
 * so both consume one source. Returns each file's trimmed content; missing or
 * unreadable files are simply omitted (no crash).
 */
export function readHotTierFiles(workspaceRoot: string): string[] {
  const parts: string[] = [];
  for (const rel of ['resources/arch-critical.md', 'resources/lessons-critical.md']) {
    const resolved = resolveCodevFile(rel, workspaceRoot);
    if (!resolved) continue;
    try {
      const content = fs.readFileSync(resolved, 'utf-8').trim();
      if (content) parts.push(content);
    } catch {
      // Non-fatal: a hot file that can't be read is omitted.
    }
  }
  return parts;
}

/**
 * Hot files surfaced into the interactive root docs as Claude Code `@import` lines.
 * `diskRelPath` is the literal on-disk location (relative to the importing doc's dir
 * = workspace root); `importLine` is the `@`-prefixed path Claude Code expands into
 * context at session launch. `copyHotTierDefaults` materializes each file at
 * codev/resources/ on init/adopt/update, so the import target is present there.
 *
 * The emit predicate is a literal existence check at `diskRelPath`, NOT the four-tier
 * resolver: an `@import` is a concrete path Claude Code reads from disk relative to
 * the doc, so a skeleton-only (tier-4) fallback would produce a dangling import that
 * never resolves. We emit a line only when the file truly sits at codev/resources/.
 */
const HOT_IMPORTS: ReadonlyArray<{ diskRelPath: string; importLine: string }> = [
  { diskRelPath: 'codev/resources/arch-critical.md', importLine: '@codev/resources/arch-critical.md' },
  { diskRelPath: 'codev/resources/lessons-critical.md', importLine: '@codev/resources/lessons-critical.md' },
];

/**
 * Render the managed block (markers + intro + `@import` lines), or '' if neither
 * hot file is present (in which case callers leave the doc untouched).
 *
 * Spec 987 originally inlined a verbatim copy of the hot files here; #1119 replaced
 * that with Claude Code `@import` lines so the hot files stay the single source of
 * truth — no copy to drift. Claude Code expands `@path` imports into context at
 * session launch (always-on, transcluded — not lazy), giving the same guarantee as
 * inlining minus the drift footgun. A line is emitted only if its hot file is on disk.
 */
export function renderHotContextBlock(workspaceRoot: string): string {
  const imports = HOT_IMPORTS
    .filter((h) => fs.existsSync(path.join(workspaceRoot, h.diskRelPath)))
    .map((h) => h.importLine);
  if (imports.length === 0) return '';
  return [
    HOT_BLOCK_BEGIN,
    '',
    '<!-- Generated by `codev init` / `codev update` from the hot files',
    '     (codev/resources/{arch,lessons}-critical.md). Do not edit here — edit the hot',
    '     files. The @import lines below are expanded into context at session launch. -->',
    '',
    '# Always-On Engineering Context (hot tier)',
    '',
    'Curated, always-on guidance — consult before deciding. Use each "consult when…"',
    'map to open the full arch.md / lessons-learned.md when relevant.',
    '',
    ...imports,
    '',
    HOT_BLOCK_END,
  ].join('\n');
}

/**
 * Upsert the managed block into a root-doc's content, non-destructively.
 * - Markers present  → replace everything between them (inclusive) with `block`.
 * - Markers absent    → insert `block` after the first H1 (or at the top if none).
 * User content outside the markers is always preserved. Idempotent.
 */
export function upsertHotContextBlock(docContent: string, block: string): string {
  if (block === '') return docContent;

  const begin = docContent.indexOf(HOT_BLOCK_BEGIN);
  const end = docContent.indexOf(HOT_BLOCK_END);
  if (begin !== -1 && end !== -1 && end > begin) {
    const before = docContent.slice(0, begin);
    const after = docContent.slice(end + HOT_BLOCK_END.length);
    return before + block + after;
  }

  const lines = docContent.split('\n');
  const h1Idx = lines.findIndex((l) => l.startsWith('# '));
  if (h1Idx === -1) {
    return `${block}\n\n${docContent}`;
  }
  const head = lines.slice(0, h1Idx + 1).join('\n');
  const tail = lines.slice(h1Idx + 1).join('\n');
  return `${head}\n\n${block}\n${tail}`;
}

/**
 * Write/refresh the managed block in CLAUDE.md and AGENTS.md under `targetDir`,
 * resolving hot files from `workspaceRoot` (four-tier). Non-clobbering: only the
 * managed block changes. A root doc that doesn't exist is skipped (init/adopt
 * create them via copyRootFiles first). Returns the names of the files changed.
 */
export function syncHotContextBlock(targetDir: string, workspaceRoot: string = targetDir): string[] {
  const block = renderHotContextBlock(workspaceRoot);
  if (block === '') return [];

  const changed: string[] = [];
  for (const name of ROOT_DOCS) {
    const p = path.join(targetDir, name);
    if (!fs.existsSync(p)) continue;
    const before = fs.readFileSync(p, 'utf-8');
    const after = upsertHotContextBlock(before, block);
    if (after !== before) {
      fs.writeFileSync(p, after);
      changed.push(name);
    }
  }
  return changed;
}
